### ISSUE TITLE
NiceHash POW Not Working. repo(Both Nicehash-test/stratum)

### ISSUE THREAD

**Issue by frode88** [DurianStallSingapore/Zilliqa-Mining-Proxy#24]
Hi. When Proxy have Activ order and running fake/real pow and proxy Get solution on fake/real pow its disconneted worker from Nicehash And same issue with PhonixMiner. Can you please take look at it? thank you.
Here Some Pictures.
![1](https://user-images.githubusercontent.com/22121200/63629811-e54a2d00-c614-11e9-93ca-2cc89441e632.png)
![2](https://user-images.githubusercontent.com/22121200/63629812-e5e2c380-c614-11e9-829e-9cd7cb37a591.png)
![1](https://user-images.githubusercontent.com/22121200/63653143-3ff49d80-c769-11e9-8e3c-d7b6bcbb6063.PNG)
![1](https://user-images.githubusercontent.com/22121200/63657340-e4de9d00-c7a0-11e9-969e-d448fcd500aa.PNG)
![1](https://user-images.githubusercontent.com/22121200/63659560-4c511880-c7b2-11e9-8b24-cf8a3f6b2249.PNG)

**Comment by ShengguangXiao** [comment]
@frode88 Did yo register the pool user in the mining proxy. The 0x582xxxxxxxxxxxxxxxxxxxxxxxxxxxx3b84 is the pubkey need to register.

pool_user: "0x582xxxxxxxxxxxxxxxxxxxxx3b84.stratumWorker"

**Comment by frode88** [comment]
> @frode88 Did yo register the pool user in the mining proxy. The 0x582xxxxxxxxxxxxxxxxxxxxxxxxxxxx3b84 is the pubkey need to register.
> 
> pool_user: "0x582xxxxxxxxxxxxxxxxxxxxx3b84.stratumWorker"

Hi. If you mean mining adress. Yes i did register. My node also registerd at the proxy siden.
![1](https://user-images.githubusercontent.com/22121200/63662157-b6bb8600-c7bd-11e9-9d7a-99fa95d8fb00.png)
![2](https://user-images.githubusercontent.com/22121200/63662160-b91de000-c7bd-11e9-86ff-bfa05c2122f5.png)

**Comment by ShengguangXiao** [comment]
What's the value you set in "pool_user" in pool.conf file?

**Comment by frode88** [comment]
@ShengguangXiao  Hi. Here is my pool.conf
![4](https://user-images.githubusercontent.com/22121200/63662379-858f8580-c7be-11e9-96ac-df5b67309cbc.PNG)

**Comment by frode88** [comment]
@ShengguangXiao Hi. I just put new adress and use numbers as name after adress and it worked. weird thing. thank you anway.
