### ISSUE TITLE
fixed

### ISSUE THREAD

**Issue by sniper-noob** [DurianStallSingapore/Zilliqa-Mining-Proxy#28]
.

**Comment by frode88** [comment]
im not sure if it this part? or any way to round up the numbers..


        for order in my_orders:
            order_number = order["id"]
            my_order_price = float(order["price"])
            top_price = self.get_top_price(top_n=top_n, excluded_orders=excluded_orders,
                                                 min_limit_speed=nice_hash_min_limit_speed,
                                                 min_accepted_speed=nice_hash_min_accepted_speed,
                                                 max_price=max_price)
            logging.info(f"My order price {my_order_price}, nice hash top price {top_price}")

            if top_price > max_price:
                logging.warning(f"NiceHash: max price, {top_price} > {max_price}")
                top_price = max_price
            if my_order_price < top_price:
                logging.warning(f"NiceHash: set order {order_number} price to {top_price:.4f}")
                retry = 20
                while retry > 0:
                    retry -= 1
                    resp = self.set_price_hashpower_order(order_number, top_price + random.uniform(0.001, 0.01), self.config['algo'], self.algorithms)
                    logging.warning(f"NiceHash: set price response {resp}")
                    if "RPC flood detected" not in resp.get("error", ""):
                        break
                    time.sleep(0.5)

**Comment by frode88** [comment]
@ShengguangXiao
