### ISSUE TITLE
setuptools is missing

### ISSUE THREAD

**Issue by dtompichayut** [DurianStallSingapore/Zilliqa-Mining-Proxy#7]
```
coreclear@cc01:~/Zilliqa-Mining-Proxy$ date
Wed Jan 23 22:48:49 +07 2019
coreclear@cc01:~/Zilliqa-Mining-Proxy$ sudo python setup.py develop
Traceback (most recent call last):
  File "setup.py", line 22, in <module>
    from setuptools import setup
ImportError: No module named setuptools
```

**Comment by deepgully** [comment]
are you using python3.6+?

**Comment by dtompichayut** [comment]
After install python 3.7.2 follow this link
[https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/](https://tecadmin.net/install-python-3-7-on-ubuntu-linuxmint/)
and run with "python3.7" instead of "python"
it can build and start successfully
